import { expect, test } from "@playwright/test";
import { expandedWorkspace } from "./workspace-fixture";
import { finishFixtureGames } from "./fixture-games";

test("confirmed current Stockfish Elo reaches every viewer; cancel and stale confirmations change nothing", async ({ page, context }) => {
  await finishFixtureGames(page.request);
  const original = await (await page.request.post("/api/games", { data: { stockfish_elo: 3100, initial_time_ms: 3600000 } })).json();
  const viewer = await context.newPage();
  await page.goto(`/games/${original.id}`);
  await viewer.goto(`/games/${original.id}`);
  await expandedWorkspace(page);
  await expect(page.getByLabel("Connection live")).toBeVisible();
  const edit = page.getByRole("group", { name: "Current black Stockfish" });
  await expect(edit.getByLabel("Current black strength", { exact: true })).toContainText("3100 target Elo");
  await edit.getByLabel("Current black proposed Elo").fill("1400");
  await edit.getByRole("button", { name: "Update current black Stockfish" }).click();
  await expect(page.getByRole("dialog")).toContainText("Update the current Stockfish Elo rating to 1400?");
  await page.getByRole("dialog").getByRole("button", { name: "Cancel", exact: true }).click();
  const cancelled = await (await page.request.get(`/api/games/${original.id}`)).json();
  expect(cancelled.revision).toBe(original.revision);
  expect(cancelled.lifecycle).toBe("running");
  expect(cancelled.black_player).toEqual(original.black_player);
  await edit.getByRole("button", { name: "Update current black Stockfish" }).click();
  await page.getByRole("button", { name: "Confirm strength update" }).click();
  await expect(viewer.getByRole("heading", { name: "Human vs Stockfish 1400", exact: true })).toBeVisible();
  await expect(edit.getByLabel("Current black strength", { exact: true })).toContainText("1400 target Elo");
  const changed = await (await page.request.get(`/api/games/${original.id}`)).json();
  expect(changed.fen).toBe(original.fen); expect(changed.moves).toEqual(original.moves);
  expect(changed.lifecycle).toBe("paused"); expect(changed.engine.target_elo).toBe(1400);
  await edit.getByLabel("Current black proposed Elo").fill("1500");
  await edit.getByRole("button", { name: "Update current black Stockfish" }).click();
  await viewer.request.post(`/api/games/${original.id}/resume`, { data: { expected_revision: changed.revision } });
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const stale = await (await page.request.get(`/api/games/${original.id}`)).json();
  expect(stale.black_player.settings.target_elo).toBe(1400);
  await page.reload(); await expandedWorkspace(page);
  await expect(edit.getByLabel("Current black proposed Elo")).toHaveValue("1400");
  await expect(page.getByRole("group", { name: "Current white Stockfish" })).toHaveCount(0);
  await viewer.close();
});
